services:
    pure-python-service:
        profiles: ["pure-python"]
        build:
            dockerfile: ./Dockerfile.pure-python
            context: .
        container_name: quest-python-cpu
        restart: no
        volumes:
            - ./artifacts/log:/app/log
            - ./artifacts/cache:/app/cache
            - ./artifacts/experiments:/app/experiments
            - ./humn:/app/humn
            - ./core:/app/core
            - ./implementations:/app/implementations
            - ./tasks:/app/tasks
        environment:
            - ERROR_LOG=/app/log/error.log
            - LOG_LEVEL=info
            - PYTHONUNBUFFERED=TRUE
            - TF_CPP_MIN_LOG_LEVEL=0
        env_file:
            - ./secrets.env
        ports:
            - "127.0.0.1:43690:43690"
        networks:
            - app_network
    torch-cuda-service:
        profiles: ["torch-cuda"]
        build:
            dockerfile: ./Dockerfile.torch-cuda
            context: .
        container_name: thinking-cuda-torch
        restart: no
        volumes:
            - ./artifacts/log/:/app/log
            - ./artifacts/cache:/app/cache
            - ./artifacts/experiments:/app/experiments
            - ./humn:/app/humn
            - ./core:/app/core
            - ./implementations:/app/implementations
            - ./tasks:/app/tasks
        environment:
            - ERROR_LOG=/app/log/error.log
            - LOG_LEVEL=info
            - PYTHONUNBUFFERED=TRUE
            - TF_CPP_MIN_LOG_LEVEL=0
        env_file:
            - ./secrets.env
        ports:
            - "127.0.0.1:43690:43690"
        networks:
            - app_network
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
    torch-rocm-service:
        profiles: ["torch-rocm"]
        build:
            dockerfile: ./Dockerfile.torch-rocm
            context: .
        container_name: thinking-rocm-torch
        restart: no
        volumes:
            - ./artifacts/log/:/app/log
            - ./artifacts/cache:/app/cache
            - ./artifacts/experiments:/app/experiments
            - ./humn:/app/humn
            - ./core:/app/core
            - ./implementations:/app/implementations
            - ./tasks:/app/tasks
        environment:
            - ERROR_LOG=/app/log/error.log
            - LOG_LEVEL=info
            - PYTHONUNBUFFERED=TRUE
            - TF_CPP_MIN_LOG_LEVEL=0
        env_file:
            - ./secrets.env
        ports:
            - "127.0.0.1:43690:43690"
        networks:
            - app_network
        devices:
            - /dev/kfd
            - /dev/dri
        security_opt:
            - seccomp:unconfined
    torch-cpu-service:
        profiles: ["torch-cpu"]
        build:
            dockerfile: ./Dockerfile.torch-cpu
            context: .
        container_name: thinking-cpu-torch
        restart: no
        volumes:
            - ./artifacts/log:/app/log
            - ./artifacts/cache:/app/cache
            - ./artifacts/experiments:/app/experiments
            - ./humn:/app/humn
            - ./core:/app/core
            - ./implementations:/app/implementations
            - ./tasks:/app/tasks
        environment:
            - ERROR_LOG=/app/log/error.log
            - LOG_LEVEL=info
            - PYTHONUNBUFFERED=TRUE
            - TF_CPP_MIN_LOG_LEVEL=0
        env_file:
            - ./secrets.env
        ports:
            - "127.0.0.1:43690:43690"
        networks:
            - app_network
networks:
    app_network:
        driver: bridge
